In [1]:

import asyncio
import warnings
import pandas as pd
from pathlib import Path

# Парсеры
from antimony import antimony_parser
from westmetall import westmetall_async
from lme import lme_selenium_async
from lbma import lbma_prescious_async

from cbr import cb_currency, cb_metalls
from nbk import nbk_tenge_async
from shmet import shmet_optimized_async
from kitco import kitco_parser_async

# Сервисные функции из service_layer
from service_layer import (
    read_db,
    save_db,
    check_df,
    check_and_save_pair,
    show_db,
    excel_to_csv_db
)

warnings.filterwarnings("ignore")


# ================================================================
# Пути к базам (реальная структура проекта)
# ================================================================
LME_PATH = Path("lme/data/LME_db_new.xlsx")
WESTMETALL_PATH = Path("westmetall/data/LME_westmetall_db.xlsx")

KITCO_PATH = Path("kitco/data/kitko_db.xlsx")
LBMA_PATH = Path("lbma/data/lbma_kitco_subs.xlsx")

ANTIMONY_PATH = Path("antimony/data/antimony.xlsx")

CB_CURRENCY_PATH = Path("cbr/data/cb_currency.xlsx")
CB_METALLS_PATH = Path("cbr/data/cb_metalls.xlsx")

NBK_PATH = Path("nbk/data/nbk_tenge.xlsx")
SHMET_PATH = Path("shmet/data/shmet_historical.xlsx")


# ================================================================
# Проверка целостности парных баз
# ================================================================
def db_check():
    """
    Проверка целостности парных баз с очисткой дубликатов
    и сохранением первого (более раннего) вхождения.
    """
    print("Проверка LME / Westmetall...")
    check_and_save_pair(
        LME_PATH,
        WESTMETALL_PATH,
        pair_name="LME / Westmetall",
        index=False,
    )

    print("Проверка Kitco / LBMA...")
    check_and_save_pair(
        KITCO_PATH,
        LBMA_PATH,
        pair_name="Kitco / LBMA",
        index=False,
    )
    
async def main():
    print("Parsing started...")

    tasks = {
        "lme": lme_selenium_async(),
        "antimony": antimony_parser(),
        "westmetall": westmetall_async(),
        "lbma": lbma_prescious_async(),
        "kitco": kitco_parser_async(),
        "cb_currency": cb_currency(),
        "cb_metalls": cb_metalls(),
        "nbk": nbk_tenge_async(),
        "shmet": shmet_optimized_async(),
    }

    # return_exceptions=True — чтобы падение одного парсера
    # не останавливало остальные
    results = await asyncio.gather(
        *tasks.values(),
        return_exceptions=True,
    )

    for name, result in zip(tasks.keys(), results):
        if isinstance(result, Exception):
            print(f"❌ Ошибка в {name}: {result}")

    print("All tasks are done!")
    print("+" * 64)
    print("Checking DB...")

    db_check()

    print("DB check completed!")
    print("+" * 64)
    print("Visual control")
    print("+" * 64)
    
    print("Converting Excel to CSV...")
    excel_to_csv_db()
    print("CSV conversion completed!")

    # Базовые металлы
    show_db("lme_selenium_db", LME_PATH, sheet_name=0)
    show_db("westmetall_db", WESTMETALL_PATH, sheet_name=0)

    # Драгоценные металлы
    show_db("kitco_db", KITCO_PATH, sheet_name=0)
    show_db("lbma_precious_db", LBMA_PATH, sheet_name=0)

    # Антимоний
    show_db("antimony_db", ANTIMONY_PATH, sheet_name=0)

    # ЦБ РФ: валюты (каждая на своем листе)
    for currency in [
        "USD",
        "EUR",
        "British_Pound",
        "China_Yuan",
        "Japanese_Yen",
        "Swiss_Franc",
    ]:
        show_db(
            f"cb_currency ({currency})",
            CB_CURRENCY_PATH,
            sheet_name=currency,
        )

    # ЦБ РФ: металлы
    show_db("cb_metalls_db", CB_METALLS_PATH, sheet_name=0)

    # Казахстан и SHMET
    show_db("nbk_tenge_db", NBK_PATH, sheet_name=0)
    show_db("shmet_historical_db", SHMET_PATH, sheet_name=0, show_head=True)


# Для Jupyter используем await, а не asyncio.run()
await main()

Parsing started...
🚀 LME parsing started...
antimony parsing is DONE
NBK_tenge parsing is DONE! (1705 строк)
✅ LME_main is done!!!
CB_metalls parsing is DONE!
USD is done!
EUR is done!
Australian_Dollar is done!
China_Yuan is done!
British_Pound is done!
Kazakhstan_Tenge is done!
Japanese_Yen is done!
Swiss_Franc is done!
CB_currency parsing is DONE!
WESTMETALL is done!!!
Произошла ошибка KITCO: Не найдены блоки <div class='grid'> на странице Kitco
SHMET is done!!!
[LBMA/Selenium] Открываем страницу LBMA...
[LBMA/Selenium] Обрабатываем Gold...
[LBMA/Selenium] Сетевых ответов от prices.lbma.org.uk: 1
[LBMA/Selenium] Gold: получено 10 строк
[LBMA/Selenium] Обрабатываем Silver...
[LBMA/Selenium] Сетевых ответов от prices.lbma.org.uk: 1
[LBMA/Selenium] Silver: получено 10 строк
[LBMA/Selenium] Обрабатываем Platinum...
[LBMA/Selenium] Сетевых ответов от prices.lbma.org.uk: 2
[LBMA/Selenium] Platinum: получено 10 строк
[LBMA/Selenium] Обрабатываем Palladium...
[LBMA/Selenium] Сетевых ответов от prices.lbma.org.uk: 1
[LBMA/Selenium] Palladium: получено 10 строк
[LBMA/Selenium] is done!!!
All tasks are done!
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Checking DB...
Проверка LME / Westmetall...
LME / Westmetall: добавлены пропущенные даты и удалены дубликаты
Проверка Kitco / LBMA...
Kitco / LBMA: добавлены пропущенные даты и удалены дубликаты
DB check completed!
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Visual control
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Converting Excel to CSV...
Поиск Excel файлов...
Найдено 9 Excel файлов
Конвертация в CSV...
✅ cb_currency.xlsx -> cb_currency.csv
✅ cb_metalls.xlsx -> cb_metalls.csv
✅ antimony.xlsx -> antimony.csv
✅ shmet_historical.xlsx -> shmet_historical.csv
✅ LME_westmetall_db.xlsx -> LME_westmetall_db.csv
✅ nbk_tenge.xlsx -> nbk_tenge.csv
✅ LME_db_new.xlsx -> LME_db_new.csv
✅ lbma_kitco_subs.xlsx -> lbma_kitco_subs.csv
✅ kitko_db.xlsx -> kitko_db.csv
Конвертация завершена!
CSV conversion completed!
lme_selenium_db

           date    lead  nickel    zink    tin  aluminium   copper
1196 2026-09-28  1886.0   16050  3957.0  53750     3248.5  14544.5
1197 2026-09-29  1876.0   15860  3977.0  53950     3225.5  14474.5
1198 2026-09-30  1856.0   15860  3954.0  54075     3204.0  14487.0
1199 2026-10-01  1837.0   15570  3834.0  54400     3120.0  14335.0
1200 2026-10-02  1827.0   15435  3798.0  54355     3109.5  14355.0

westmetall_db

           date  aluminium   copper    lead  nickel    zink    tin
1196 2026-09-28     3248.5  14544.5  1886.0   16050  3957.0  53750
1197 2026-09-29     3225.5  14474.5  1876.0   15860  3977.0  53950
1198 2026-09-30     3204.0  14487.0  1856.0   15860  3954.0  54075
1199 2026-10-01     3120.0  14335.0  1837.0   15570  3834.0  54400
1200 2026-10-02     3109.5  14355.0  1827.0   15435  3798.0  54355

kitco_db

            Date     Gold  Silver  Platinum  Palladium
14857 2026-09-28  4144.55  61.330   1731.85    1219.25
14858 2026-09-29  4163.40  60.865   1690.25    1218.60
14859 2026-09-30  4176.30  60.730   1714.10    1222.00
14860 2026-10-01  4151.65  60.920   1727.35    1193.95
14861 2026-10-02  4190.05  61.035   1743.80    1196.55

lbma_precious_db

            Date     Gold  Silver  Platinum  Palladium
14857 2026-09-28  4144.55  61.330   1731.85    1219.25
14858 2026-09-29  4163.40  60.865   1690.25    1218.60
14859 2026-09-30  4176.30  60.730   1714.10    1222.00
14860 2026-10-01  4151.65  60.920   1727.35    1193.95
14861 2026-10-02  4190.05  61.035   1743.80    1196.55

antimony_db

          Date  Avg(CNY/mt,VAT included)  Avg With Rate(USD/mt,VAT included)
630 2026-09-23                  107000.0                            14098.79
631 2026-09-24                  107000.0                            14071.34
632 2026-09-28                  107000.0                            14065.28
633 2026-09-29                  107000.0                            14075.11
634 2026-09-30                  107000.0                            14078.87

cb_currency (USD)

          date  unit  nominal
922 2026-09-29     1  84.4075
923 2026-09-30     1  84.4283
924 2026-10-01     1  83.5588
925 2026-10-02     1  83.2454
926 2026-10-03     1  83.4839

cb_currency (EUR)

          date  unit  nominal
922 2026-09-29     1  96.2499
923 2026-09-30     1  96.0625
924 2026-10-01     1  94.8810
925 2026-10-02     1  94.5252
926 2026-10-03     1  94.3201

cb_currency (British_Pound)

          date  unit   nominal
922 2026-09-29     1  111.8062
923 2026-09-30     1  111.8759
924 2026-10-01     1  110.4146
925 2026-10-02     1  110.5915
926 2026-10-03     1  110.2989

cb_currency (China_Yuan)

          date  unit  nominal
922 2026-09-29     1  12.5629
923 2026-09-30     1  12.5764
924 2026-10-01     1  12.4732
925 2026-10-02     1  12.4028
926 2026-10-03     1  12.4328

cb_currency (Japanese_Yen)

          date  unit  nominal
922 2026-09-29   100  53.5071
923 2026-09-30   100  53.6325
924 2026-10-01   100  53.1038
925 2026-10-02   100  52.6370
926 2026-10-03   100  52.8112

cb_currency (Swiss_Franc)

          date  unit   nominal
922 2026-09-29     1  101.5612
923 2026-09-30     1  101.2208
924 2026-10-01     1  100.3348
925 2026-10-02     1   99.6593
926 2026-10-03     1  100.7894

cb_metalls_db

          date      gold  silver  platinum  palladium
922 2026-09-29  11563.48  176.44   4800.10    3410.52
923 2026-09-30  11250.09  166.48   4700.99    3309.57
924 2026-10-01  11184.87  163.51   4540.82    3273.74
925 2026-10-02  11177.45  162.54   4587.62    3270.56
926 2026-10-03  11143.31  163.51   4636.32    3204.64

nbk_tenge_db

           date  Числовое значение  ДОЛЛАР США
1700 2026-09-29                  1      441.77
1701 2026-09-30                  1      439.37
1702 2026-10-01                  1      440.86
1703 2026-10-02                  1      441.91
1704 2026-10-03                  1      447.73

shmet_historical_db

        date  price     unit
0 2020-01-10  48605  Yuan/MT
1 2020-01-14  48990  Yuan/MT
2 2020-01-15  49060  Yuan/MT
3 2020-01-16  48950  Yuan/MT
4 2020-01-17  48930  Yuan/MT